language: generic
services:
  - docker

env:
  global:
    - BUILDER="catkin_make"
    - VERBOSE_TESTS="true"
    # - UPSTREAM_WORKSPACE='github:rarrais/rospy_urdf_to_rviz_converter#ros_package'
  matrix:
    - ROS_DISTRO="melodic"

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh