#!/usr/bin/env python3

# Imports

# ROS imports

# ATOM imports
from atom_core.system import execColored


def main():

    atom_examples = ['rrbot', 'rrcbot', 'rdbot', 'rlbot', 'rihbot',
                     'rihmpbot', 'riwbot', 'mrjbot', 'riwbot', 'scpjbot']
    for atom_example in atom_examples:
        cmd = 'rosrun ' + atom_example + '_calibration configure'
        execColored(cmd)


if __name__ == "__main__":
    main()
