#!/usr/bin/env python3

# stdlib

# 3rd-party
import rospy
from interactive_markers.interactive_marker_server import *
from interactive_markers.menu_handler import *
from visualization_msgs.msg import *
from gazebo_msgs.srv import GetModelState, SetModelConfiguration, SetModelConfigurationRequest


if __name__ == "__main__":

    #     # Parse command line arguments
    #     ap = argparse.ArgumentParser(
    #         description='Interactive manipulation of pattern pattern in rviz.')
    #     ap.add_argument("-ms", "--mesh_resource", type=str, help='full path to calibration pattern dae.',
    #                     default='package://atom_worlds/pattern/models/charuco_800x600_5x5_100/charuco_800x600_5x5_100.dae')
    #     ap.add_argument("-mn", "--model_name", type=str, help='Model name in gazebo.',
    #                     default='charuco_800x600_5x5_100')
    #
    #     args = vars(ap.parse_args(args=filterLaunchArguments(sys.argv)))

    rospy.init_node("set_robot_pose")

    service_name = '/gazebo/set_model_configuration'
    rospy.wait_for_service(service_name)
    print('Service ' + service_name + ' found')

    request_message = SetModelConfigurationRequest()
    request_message.model_name = 'robot'
    request_message.urdf_param_name = 'robot_description'
    request_message.joint_names = ['robot::shoulder_pan_joint']
    request_message.joint_positions = [5.709]

    #   -J shoulder_pan_joint 1.709
    #   -J shoulder_lift_joint -0.960
    #   -J elbow_joint -2.093
    #   -J wrist_1_joint -0.453
    #   -J wrist_2_joint 1.465
    #   -J wrist_3_joint -3.035
    #
    # string
    # string[] joint_names
    # float64[] joint_positions
    # ---

    # set_model_configuration_service = rospy.ServiceProxy(service_name, SetModelConfiguration)

    set_model_configuration_service = rospy.ServiceProxy(service_name, SetModelConfiguration)

    for i in range(1, 100):
        print('Calling service')
        response_message = set_model_configuration_service(request_message)
        print('Service response ' + str(response_message))
