#!/usr/bin/env python3

# System and standard imports
import argparse
import os
import os.path
import sys
from functools import partial

# ros imports
from atom_core.utilities import atomError,atomWarn
from interactive_markers.interactive_marker_server import InteractiveMarkerServer
import rospy

# 3rd-party imports
from colorama import Fore, Style
from pynput import keyboard

# Atom imports
from atom_core.utilities import createLambdaExpressionsForArgs
from atom_calibration.transform_corrector.pose_interactive_marker import PoseInteractiveMarker
from atom_calibration.transform_corrector.visualization import setupVisualization, visualizationFunction
from atom_core.dataset_io import (filterCollectionsFromDataset,
                                  filterSensorsFromDataset, loadResultsJSON, saveAtomDataset)


# own packages


# global variables  ... are forbidden

# -------------------------------------------------------------------------------
# --- FUNCTIONS
# -------------------------------------------------------------------------------


def printHelp():

    s = 'Drag with the left button to select objects in the 3D scene.\n' \
        ' Hold the Alt key to change viewpoint as in the Move tool.'\
        ' Holding the Shift key will allow adding to the current selection.\n'\
        ' Holding the Ctrl key will allow subtraction from the current selection.\n'\
        ' The following keys are also available:\n'\
        ' s - Save dataset\n'\
        ' q - Save dataset and quit \n'
    print(s)


def keyPressedCallback(key, selection, dataset, args, depth_mode, output_file):

    if key is None:
        return
    # TODO #402 does not work if some of the collections in the middles, e.g. '1' are removed. An easy test is to run a -csf "lambda x: x in ['0', '2']"

    # print("collection_key = " + str(selection['collection_key']))
    # print("previous_collection_key = " + str(selection['previous_collection_key']))

    # Shortcut variables
    idx_collection = list(dataset['collections'].keys()).index(selection['collection_key'])
    idx_max_collection = len(dataset['collections'].keys()) - 1

    # Convert from type to string to keep uniform.

    try:
        key_char = key.char
        # print(key_char)
        if key_char == 's':  # Saves dataset.
            saveAtomDataset(output_file, dataset, freeze_dataset=True)
            print('A new dataset was saved in ' + output_file)
        elif key_char == 'q':  # Saves dataset and quits.
            saveAtomDataset(output_file, dataset, freeze_dataset=True)
            print('A new dataset was saved in ' + output_file)
            print('Exiting ...')
            selection['exit'] = True
        elif key_char == 'h':  # Prints help.
            printHelp()

    except AttributeError:
        if key == keyboard.Key.right:  # Save and move to collection + 1.
            if idx_collection < idx_max_collection:
                selection['previous_collection_key'] = selection['collection_key']
                selection['collection_key'] = list(dataset['collections'].keys())[idx_collection+1]
                print('Changed selected_collection_key to ' + str(selection['collection_key']))
                saveAtomDataset(output_file, dataset, freeze_dataset=True)

            else:
                print(Fore.RED + 'This is the last collection!!' + Fore.RESET)
        elif key == keyboard.Key.left:  # Save and move to collection - 1.
            if idx_collection > 0:
                selection['previous_collection_key'] = selection['collection_key']
                selection['collection_key'] = list(dataset['collections'].keys())[idx_collection-1]
                print('Changed selected_collection_key to ' + str(selection['collection_key']))
                saveAtomDataset(output_file, dataset, freeze_dataset=True)

            else:
                print(Fore.RED + 'This is the first collection!!' + Fore.RESET)


# -------------------------------------------------------------------------------
# --- MAIN
# -------------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("-json", "--json_file", type=str, required=True,
                    help="Json file containing input dataset.",)
    ap.add_argument("-ow", "--overwrite",
                    help="Overwrites the data_corrected.json without asking for permission.",
                    action='store_true')
    ap.add_argument(
        "-rnb", "--remove_nan_border", action='store_true',
        help="Option for the labeling of depth images. It Will run a detection of nan values in the image, searching for the actual area of the image which is used. Then, border detection will use this estimated area...",)
    ap.add_argument(
        "-rc", "--reference_collection",
        help="Reference collection to always show in blue color. Argument should be in the form 00x.", required=True)
    ap.add_argument(
        "-rs", "--reference_sensor", required=False,
        help="Sensor data to always show at reference collection in blue color. For now only lidar3d is supported.")
    ap.add_argument("-pll", "--parent_link_list", required=True, type=str,
                    help="The names of the parent frames in the TF to copy", nargs='+')
    ap.add_argument("-cll", "--child_link_list", required=True, type=str,
                    help="The names of the child frames in the TF to copy", nargs='+')
    ap.add_argument(
        "-2d", "--2d_mode", action='store_true',
        help="Interactive marker only moves in 2D. Useful for odometry transformations",)
    ap.add_argument("-s", "--marker_scale", type=float, default=0.9,
                    help='Scale of the interactive markers.')
    # ap.add_argument(
    #     "-csf", "--collection_selection_function", default=None, type=str,
    #     help="A string to be evaluated into a lambda function that receives a collection name as input and "
    #     "returns True or False to indicate if the collection should be loaded (and used in the "
    #     "optimization). The Syntax is lambda name: f(x), where f(x) is the function in python "
    #     "language. Example: lambda name: int(name) > 5 , to load only collections 6, 7, and onward.")

    # Roslaunch adds two arguments (__name and __log) that break our parser. Lets remove those.
    arglist = [x for x in sys.argv[1:] if not x.startswith('__')]
    # these args have the selection functions as strings
    args_original = vars(ap.parse_args(args=arglist))
    args = createLambdaExpressionsForArgs(args_original)  # selection functions are now lambdas

    # Arguments which are not options for transform_corrector
    args['ros_visualization'] = True
    args['show_images'] = True
    args['use_incomplete_collections'] = True
    args['remove_partial_detections'] = False
    args['collection_selection_function'] = None

    # ---------------------------------------
    # --- INITIALIZATION Read data from file
    # ---------------------------------------
    # Loads a json file containing the detections. Returned json_file has path resolved by urireader.
    dataset, json_file = loadResultsJSON(args['json_file'], args['collection_selection_function'])

    # ---------------------------------------
    # --- Filter some collections and / or sensors from the dataset
    # ---------------------------------------
    # During dataset review there is no need to filter out collections
    dataset = filterCollectionsFromDataset(dataset, args)

    output_file = os.path.join(os.path.dirname(args['json_file']), 'dataset_corrected.json')
    if os.path.exists(output_file) and args['json_file'] != output_file and not args['overwrite']:
        ans = input('The file dataset_corrected.json already exists.'
                    ' Do you want to overwrite? (Y/n)')
        if ans.lower() == 'n':
            sys.exit(0)

    dataset = filterSensorsFromDataset(dataset, args)  # filter sensors

    print('Loaded dataset containing ' + str(len(dataset['sensors'].keys())) + ' sensors and ' +
          str(len(dataset['collections'].keys())) + ' collections.')

    depth_mode = {'mode': 'detect'}

    # ---------------------------------------
    # --- Define selection
    # ---------------------------------------
    # Lets start with the first key on the collections dictionary.
    # Data structure used to save the state of navigation throughout the collections in the dataset.
    selection = {'collection_key': list(dataset['collections'].keys())[
        0], 'previous_collection_key': None, 'exit': False}

    print("Configuring visualization ... ")
    graphics = setupVisualization(dataset, args, selection['collection_key'])

    # ---------------------------------------
    # --- Define callback to navigate through collections
    # ---------------------------------------
    listener = keyboard.Listener(
        on_press=partial(
            keyPressedCallback, selection=selection, dataset=dataset, args=args,
            depth_mode=depth_mode, output_file=output_file))
    listener.start()

    # ---------------------------------------
    # Setting up interactive marker server
    # ---------------------------------------

    interactive_marker_server = InteractiveMarkerServer('transform_corrector')

    pose_markers = []
    for parent, child in zip(args['parent_link_list'], args['child_link_list']):
        print(parent, child)

        if 'transforms' not in dataset.keys():
            atomError('Dataset must have the transforms field. Perhaps you are using an old dataset.')

        name_in_dataset = parent + '-' + child
        if dataset['transforms'][name_in_dataset]['type'] == 'fixed':
            is_fixed = True
        else:
            is_fixed = False

        name = parent + '_' + child
        pose_marker = PoseInteractiveMarker(
            name=name, dataset=dataset, selection=selection, server=interactive_marker_server,
            world_link=dataset['calibration_config']['world_link'],
            parent=parent, child=child,
            is_fixed=is_fixed, two_dimensional_mode=args['2d_mode'],
            marker_scale=args['marker_scale'])

        pose_markers.append(pose_marker)

    # ---------------------------------------
    # --- Loop while displaying selected collection
    # ---------------------------------------
    print('\nPress ' + Fore.BLUE + '"h"' + Style.RESET_ALL + ' for instructions.\n')

    rate = rospy.Rate(10)  # in hertz.
    tic = rospy.Time.now()
    current_collection = 'this will not be a collection key'
    while not rospy.is_shutdown() and not selection['exit']:
        models = {'dataset': dataset, 'args': args, 'graphics': graphics}
        if selection['collection_key'] != current_collection:

            for pose_marker in pose_markers:
                pose_marker.updateMarkersFromDataset()

            current_collection = selection['collection_key']

        visualizationFunction(models=models, selection=selection)
        rate.sleep()

        # if (rospy.Time.now() - tic).to_sec() > 3:
        # tic = rospy.Time.now()

    atomWarn("If the corrections made were significant, the pattern poses might need to be recomputed with the estimatePatternPoses script. Check #984.")


if __name__ == "__main__":
    main()
